# Generated by Django 4.2.17 on 2025-03-04 09:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hospital_app', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Organization',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('address', models.TextField()),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=15)),
            ],
        ),
        migrations.CreateModel(
            name='Service',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('service_type', models.CharField(choices=[('registration', 'Registration'), ('visit', 'Doctor Visit'), ('lab_test', 'Lab Test'), ('prescription', 'Prescription')], max_length=20)),
                ('price', models.DecimalField(decimal_places=2, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='Payment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('paid', 'Paid'), ('credit', 'Credit')], default='pending', max_length=10)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('organization_letter', models.FileField(blank=True, null=True, upload_to='letters/')),
                ('signed_attachment', models.FileField(blank=True, null=True, upload_to='attachments/')),
                ('service', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='finance.service')),
                ('visitor', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='payments', to='hospital_app.visit')),
            ],
        ),
    ]
