# Generated by Django 4.2.17 on 2025-03-05 15:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('registrar', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Drug',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('stock_quantity', models.PositiveIntegerField(default=0)),
            ],
        ),
        migrations.CreateModel(
            name='LabResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('is_finalized', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='LabTest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, unique=True)),
                ('description', models.TextField(blank=True, null=True)),
                ('price', models.DecimalField(decimal_places=2, default=0.0, max_digits=10)),
            ],
        ),
        migrations.CreateModel(
            name='LabTestCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(choices=[('hematology_test', 'Hematology Tests'), ('microbiology_test', 'Microbiology Tests'), ('clinical_chemistry_test', 'Clinical Chemistry Test'), ('urinalysis_and_body_fluid_test', 'Urinalysis & Body Fluids'), ('immunology_test', 'Immunology & Serology'), ('endocrinology_test', 'Endocrinology Test'), ('tumer_test', 'Tumor Markers'), ('covid_19', 'COVID-19 RT-PCR')], max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='LabTestRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_urgent', models.BooleanField(default=False)),
                ('requested_at', models.DateTimeField(auto_now_add=True)),
                ('status', models.CharField(choices=[('requested', 'Requested'), ('processing', 'Processing'), ('completed', 'Completed'), ('rejected', 'Rejected')], default='requested', max_length=20)),
                ('notes', models.TextField(blank=True, null=True)),
                ('is_payed', models.BooleanField(default=False)),
                ('requested_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_requests', to=settings.AUTH_USER_MODEL)),
                ('tests', models.ManyToManyField(related_name='lab_test_requests', to='hospital_app.labtest')),
            ],
            options={
                'ordering': ['-requested_at'],
            },
        ),
        migrations.CreateModel(
            name='Prescription',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date_prescribed', models.DateTimeField(auto_now_add=True)),
                ('is_dispensed', models.BooleanField(default=False)),
                ('is_payed', models.BooleanField(default=False)),
                ('prescribed_by', models.ForeignKey(limit_choices_to={'role': 'doctor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Visit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visit_date', models.DateTimeField(auto_now_add=True)),
                ('chief_complaint', models.TextField(blank=True)),
                ('urgency', models.CharField(choices=[('urgent', 'Urgent'), ('non_urgent', 'Non-Urgent')], default='non_urgent', max_length=20)),
                ('history_of_present_illness', models.TextField(blank=True)),
                ('physical_examination', models.TextField(blank=True)),
                ('investigations', models.TextField(blank=True)),
                ('management_plan', models.TextField(blank=True)),
                ('clinical_diagnosis', models.TextField(blank=True)),
                ('treatment_plan', models.TextField(blank=True)),
                ('advice', models.TextField(blank=True)),
                ('next_appointment_date', models.DateField(blank=True, null=True)),
                ('physician_signature', models.CharField(blank=True, max_length=100)),
                ('is_active', models.BooleanField(default=True)),
                ('status', models.CharField(choices=[('pending_payment', 'Pending Payment'), ('triage', 'Triage'), ('ward_transfer', 'Transferred to Ward'), ('seen', 'Seen'), ('sent_to_lab', 'Sent to Lab'), ('sys_exam', 'System Examination'), ('completed', 'Completed')], default='pending_payment', max_length=20)),
                ('assigned_ward', models.CharField(choices=[('ipd', 'In Patient Department'), ('opd', 'Out Patient Department'), ('er', 'Emergency')], default='opd', max_length=20)),
                ('attending_physician', models.ForeignKey(blank=True, limit_choices_to={'role': 'doctor'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('patient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='visits', to='registrar.patient')),
            ],
        ),
        migrations.CreateModel(
            name='TriageRecord',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('blood_pressure', models.CharField(blank=True, max_length=20)),
                ('pulse_rate', models.CharField(blank=True, max_length=15, null=True)),
                ('respiratory_rate', models.CharField(blank=True, max_length=10, null=True)),
                ('temperature', models.CharField(blank=True, max_length=4, null=True)),
                ('weight', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('height', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('bmi', models.DecimalField(blank=True, decimal_places=1, max_digits=5, null=True)),
                ('oxygen_saturation', models.CharField(blank=True, max_length=4, null=True)),
                ('status', models.CharField(choices=[('pending', 'Pending'), ('completed', 'Completed')], default='pending', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('recorded_by', models.ForeignKey(blank=True, limit_choices_to={'role': 'nurse'}, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='triage_record', to='hospital_app.visit')),
            ],
        ),
        migrations.CreateModel(
            name='SystemExamination',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('heent', models.TextField(blank=True)),
                ('lungs', models.TextField(blank=True)),
                ('cardiovascular', models.TextField(blank=True)),
                ('gastrointestinal', models.TextField(blank=True)),
                ('genitourinary', models.TextField(blank=True)),
                ('musculoskeletal', models.TextField(blank=True)),
                ('neurological', models.TextField(blank=True)),
                ('visit', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='system_examination', to='hospital_app.visit')),
            ],
        ),
        migrations.CreateModel(
            name='PrescriptionItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('dosage', models.CharField(max_length=100)),
                ('quantity', models.PositiveIntegerField()),
                ('price_per_unit', models.DecimalField(decimal_places=2, max_digits=10)),
                ('drug', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='hospital_app.drug')),
                ('prescription', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='items', to='hospital_app.prescription')),
            ],
        ),
        migrations.AddField(
            model_name='prescription',
            name='visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='prescriptions', to='hospital_app.visit'),
        ),
        migrations.CreateModel(
            name='LabTestResult',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_value', models.CharField(blank=True, max_length=255, null=True)),
                ('result_file', models.FileField(blank=True, null=True, upload_to='lab_results/')),
                ('performed_at', models.DateTimeField(auto_now_add=True)),
                ('is_retest', models.BooleanField(default=False)),
                ('lab_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='results', to='hospital_app.labtestrequest')),
                ('performed_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='lab_results', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.AddField(
            model_name='labtestrequest',
            name='visit',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lab_requests', to='hospital_app.visit'),
        ),
        migrations.CreateModel(
            name='LabTestParameter',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('unit', models.CharField(blank=True, max_length=50, null=True)),
                ('reference_range', models.CharField(blank=True, max_length=100, null=True)),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='parameters', to='hospital_app.labtest')),
            ],
        ),
        migrations.AddField(
            model_name='labtest',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tests', to='hospital_app.labtestcategory'),
        ),
        migrations.CreateModel(
            name='LabResultItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('result_data', models.JSONField(default=dict)),
                ('lab_result', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_items', to='hospital_app.labresult')),
                ('test', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='result_items', to='hospital_app.labtest')),
            ],
        ),
        migrations.AddField(
            model_name='labresult',
            name='lab_request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='lab_result', to='hospital_app.labtestrequest'),
        ),
        migrations.AddField(
            model_name='labresult',
            name='reviewed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_results', to=settings.AUTH_USER_MODEL),
        ),
    ]
