# Generated by Django 4.2.17 on 2025-03-06 14:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0002_alter_triagerecord_temperature'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='advice',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='chief_complaint',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='clinical_diagnosis',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='history_of_present_illness',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='investigations',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='management_plan',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='physical_examination',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='visit',
            name='treatment_plan',
            field=models.TextField(blank=True, null=True),
        ),
    ]
