# Generated by Django 4.2.17 on 2025-03-06 16:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hospital_app', '0003_alter_visit_advice_alter_visit_chief_complaint_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='visit',
            name='status',
            field=models.CharField(choices=[('pending_payment', 'Pending Payment'), ('triage', 'Triage'), ('ward_transfer', 'Transferred to Ward'), ('seen', 'Seen'), ('sent_to_lab', 'Sent to Lab'), ('sys_exam', 'System Examination'), ('prescribed', 'Prescribed'), ('completed', 'Completed')], default='pending_payment', max_length=20),
        ),
    ]
