# Generated by Django 4.2.17 on 2025-03-05 15:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Address',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(choices=[('addis ababa', 'Addis Ababa'), ('afar', 'Afar'), ('amhara', 'Amhara'), ('benishangul', 'Benishangul-Gumuz'), ('dire dawa', 'Dire Dawa'), ('gambela', 'Gambela'), ('harari', 'Harari'), ('oromia', 'Oromia'), ('sidama', 'Sidama'), ('south ethiopia', 'South Ethiopia'), ('south west ethiopia', 'South West Ethiopia'), ('central ethiopia', 'Central Ethiopia'), ('somali', 'Somali'), ('tigray', 'Tigray')], default='south ethiopia', max_length=100)),
                ('kebele', models.CharField(blank=True, max_length=100, null=True)),
                ('ketena', models.CharField(blank=True, max_length=100, null=True)),
                ('house_no', models.CharField(blank=True, max_length=100, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='Zone',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('region', models.CharField(choices=[('addis ababa', 'Addis Ababa'), ('afar', 'Afar'), ('amhara', 'Amhara'), ('benishangul', 'Benishangul-Gumuz'), ('dire dawa', 'Dire Dawa'), ('gambela', 'Gambela'), ('harari', 'Harari'), ('oromia', 'Oromia'), ('sidama', 'Sidama'), ('south ethiopia', 'South Ethiopia'), ('south west ethiopia', 'South West Ethiopia'), ('central ethiopia', 'Central Ethiopia'), ('somali', 'Somali'), ('tigray', 'Tigray')], default='south ethiopia', max_length=100)),
                ('name', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Woreda',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('zone', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='woredas', to='registrar.zone')),
            ],
        ),
        migrations.CreateModel(
            name='Patient',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('record_no', models.CharField(editable=False, max_length=8, unique=True)),
                ('first_name', models.CharField(max_length=100)),
                ('middle_name', models.CharField(max_length=100)),
                ('last_name', models.CharField(max_length=100)),
                ('dob', models.DateField()),
                ('age', models.PositiveIntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], default='M', max_length=1)),
                ('phone', models.CharField(max_length=15)),
                ('national_id', models.CharField(blank=True, max_length=20, null=True, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('address', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='registrar.address')),
            ],
        ),
        migrations.AddField(
            model_name='address',
            name='woreda',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='registrar.woreda'),
        ),
        migrations.AddField(
            model_name='address',
            name='zone',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='addresses', to='registrar.zone'),
        ),
    ]
