# Generated by Django 4.2.17 on 2025-03-06 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('registrar', '0002_appointments'),
    ]

    operations = [
        migrations.AddField(
            model_name='appointments',
            name='is_seen',
            field=models.BooleanField(default=False),
        ),
    ]
